version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    # - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    # - tagliatelle
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 150
    funlen:
      lines: 120
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - codegenComment
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - composites
    lll:
      line-length: 250
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gocyclo
          - gosec
          - lll
          - mnd
          - unparam
        path: _test\.go
      - linters:
          - gocyclo
        path: main\.go
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - funlen
        path: main.go
      - path: (.+)\.go$
        text: .* struct literal uses unkeyed fields
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
