#!/bin/bash

ARCH=$(uname -m)
case $ARCH in
  x86_64)
    BINARY_ARCH="amd64"
    ;;
  arm64)
    BINARY_ARCH="arm64"
    ;;
  *)
    echo "Unsupported architecture: $ARCH"
    exit 1
    ;;
esac

# Copy the appropriate binary
mkdir -p /usr/local/bin
cp "/tmp/xn-install/darwin-${BINARY_ARCH}/xn" /usr/local/bin/xn
chmod +x /usr/local/bin/xn

# Clean up
rm -rf /tmp/xn-install
