name: Build Darwin

on:
  workflow_call:

jobs:
  build-darwin:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Darwin PKG
        run: |
          ./scripts/build-darwin.sh ${GITHUB_REF_NAME:-dev}
