name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run go vet
        run: go vet ./...

  build-darwin:
    # MacOS runners are expensive; don't waste cycles!
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    uses: ./.github/workflows/build-darwin.yml

  build-windows:
    # Windows runners are expensive; don't waste cycles!
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    uses: ./.github/workflows/build-windows.yml
