name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run go vet
        run: go vet ./...

  build-darwin:
    uses: ./.github/workflows/build-darwin.yml
  
  build-windows:
    uses: ./.github/workflows/build-windows.yml